### ISSUE TITLE
حالت کنسلش کار نمیکنه 

### ISSUE THREAD

**Issue by lotfi1008** [fericode/Blazor.PersianDatePicker#28]
وقتی رو المان کلیک میکنی باز میشه و میتونی انتخاب کنی ولی اگه منصرف بشی دیگه هیچ جوری بسته نمیشه مگه اینکه یه تاریخ انتخاب کنی.
توی فرم های ویرایش نمیشه تاریخ رو خالی کرد تا مقدار خالی بره تو دیتابیس

**Comment by fericode** [comment]
سلام، ممنون از نقطه نظر شما. بله متوجه این مشکل بودم، آخر هفته با همکاری یکی از دوستان ردیفش می‌کنم

**Comment by fericode** [comment]
Resolved
